### ISSUE TITLE
Jsy Binding

### ISSUE THREAD

**Issue by bechang** [cuplv/cuanto#22]
Some things about implementing let-binding. This can easily get to bike-shedding, so let's try to refrain (myself included). This is about syntax, and I can't believe I am about to start a conversation about it 😄  when I always that this is not what PL is about. But there are some things that are bit tricky.

The underlying principle for JavaScripty is that we want to accept syntactically valid JavaScript, though we may accept more programs to be more natural with the abstract syntax. I don't want a separate statement and expression language in the abstract syntax, so JavaScript's statements get collapsed to expressions. (And I guess perhaps that internally for real interpreters, that's the case as well, and the statement-expression divide is simply at the concrete syntax level. For example,
```
if (true) { true } else { false }
```
at the top-level in node yields `true`.)

So, we want to support `{ let x = 3; x }` or
```
{ let x = 3
  x }
```

I think the simplest implementation is to treat the tokens `let x = 3`, `;`, and `x` as a sequence of expressions with `;` being the "no-op" expression, which would permit the above two programs, but it would also parse the concrete syntax `{ let x = 3 x }` into the same abstract syntax, which is a bit weird.

A still relatively simple alternative (and one that I implement in 3155) is to stratify into statements and expressions and to consider declarations like `let x = 3` as statements. Then, `;` becomes the empty statement (and not expression). So`{ let x = 3 x }` becomes syntactically invalid because `3 x` is not an expression. We can still embed statements in expressions as blocks `{ _stmt_ }`, so we can still express everything in the abstract syntax. I believe this is what Scala does (though I have not consulted the spec). The cost is a little bit greater disconnect between the concrete and abstract syntax.

I am leaning towards this latter option (slightly more complex but closer to JavaScript).

PR: #17

**Comment by bechang** [comment]
@bennostein @kyleheadley: Could you please comment on the above when you can?

**Comment by kyleheadley** [comment]
So JS has special consideration of the newline char? Do we need to have the same considerations? If not, then I agree that `{ let x = 3 x }` should not parse

**Comment by bechang** [comment]
Oops, I was wrong in the above. And in retrospect, kind of dumb. Of course `{ let x = 3 x }` would still parse because it would be recognized as `{ { let x = 3 } { x } }`. What the stratification restricts is that `let ...` or `;` could only appear in blocks. So `{ let x = 3; x }` is fine but `(let x = 3; x)` is not. Perhaps still useful in any case.
